version: "2.4"
services:
  messageborad:
    image: mysql:5.7
    volumes:
      - "./mysql/data:/var/lib/mysql"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: messageboard
      MYSQL_USER: ito
      MYSQL_PASSWORD: pass1234